<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $properties = [
            [
                'title' => 'Villa Sostenible con Certificación A en La Eliana',
                'slug' => 'villa-sostenible-certificacion-a-la-eliana',
                'description' => "Espectacular villa de nueva construcción con los más altos estándares de eficiencia energética. Esta propiedad cuenta con certificación energética A, lo que garantiza un consumo mínimo y el máximo confort.\n\nLa vivienda dispone de sistema de aerotermia para climatización y agua caliente, placas solares fotovoltaicas con capacidad de autoconsumo del 70%, ventanas de triple acristalamiento con rotura de puente térmico, y sistema SATE de aislamiento exterior.\n\nEl jardín incluye sistema de riego automatizado con recuperación de aguas pluviales. Materiales de construcción certificados y pinturas ecológicas en todo el interior.",
                'price' => 485000,
                'location' => 'La Eliana, Valencia',
                'address' => 'Urbanización El Bosque, 15',
                'surface' => 250,
                'rooms' => 4,
                'bathrooms' => 3,
                'year_built' => 2023,
                'property_type' => 'chalet',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 450,
                'co2_savings' => 2800,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'sate', 'aerothermy', 'solar_panels', 'rainwater_recovery', 'certified_wood', 'eco_paints'],
                'certifications' => ['Passivhaus', 'BREEAM'],
                'images' => ['/images/properties/villa-sostenible-1.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Piso Eco-Eficiente en Ruzafa',
                'slug' => 'piso-eco-eficiente-ruzafa',
                'description' => "Moderno piso reformado íntegramente con criterios de sostenibilidad en el corazón del barrio de Ruzafa. Certificación energética B conseguida tras una rehabilitación completa.\n\nLa vivienda cuenta con suelo radiante conectado a bomba de calor aerotérmica, ventanas de doble acristalamiento Climalit con control solar, y electrodomésticos de máxima eficiencia energética.\n\nUbicación perfecta para disfrutar de la vida del barrio más trendy de Valencia, con todos los servicios a pie de calle.",
                'price' => 265000,
                'location' => 'Ruzafa, Valencia',
                'address' => 'Calle Cuba, 34',
                'surface' => 95,
                'rooms' => 3,
                'bathrooms' => 2,
                'year_built' => 2022,
                'property_type' => 'piso',
                'status' => 'disponible',
                'energy_rating' => 'B',
                'co2_emissions' => 680,
                'co2_savings' => 1500,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'aerothermy', 'eco_paints'],
                'certifications' => ['LEED'],
                'images' => ['/images/properties/casa-ecologica-2.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Ático con Placas Solares en Benimaclet',
                'slug' => 'atico-placas-solares-benimaclet',
                'description' => "Luminoso ático con terraza de 40m² equipada con instalación fotovoltaica propia. Certificación energética A gracias a la combinación de energía solar y excelente aislamiento.\n\nVistas despejadas y orientación sur que maximiza el aprovechamiento de la luz natural. Sistema de domótica para control inteligente de consumos.\n\nEl edificio ha sido rehabilitado con sistema SATE y cuenta con zonas comunes eficientes.",
                'price' => 320000,
                'location' => 'Benimaclet, Valencia',
                'address' => 'Avenida Primado Reig, 78',
                'surface' => 110,
                'rooms' => 2,
                'bathrooms' => 2,
                'year_built' => 2021,
                'property_type' => 'atico',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 380,
                'co2_savings' => 2200,
                'energy_type' => 'solar',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'sate', 'solar_panels'],
                'certifications' => ['BREEAM'],
                'images' => ['/images/properties/piso-eficiente-3.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Casa Adosada Bioclimática en Godella',
                'slug' => 'casa-adosada-bioclimatica-godella',
                'description' => "Casa adosada diseñada siguiendo principios de arquitectura bioclimática. Orientación optimizada para captación solar pasiva en invierno y protección en verano.\n\nCuenta con sistema de ventilación con recuperador de calor, geotermia para climatización, y cubierta vegetal que mejora el aislamiento y reduce el efecto isla de calor.\n\nJardín con plantas autóctonas de bajo consumo hídrico.",
                'price' => 395000,
                'location' => 'Godella, Valencia',
                'address' => 'Camino del Huerto, 12',
                'surface' => 180,
                'rooms' => 4,
                'bathrooms' => 2,
                'year_built' => 2020,
                'property_type' => 'adosado',
                'status' => 'disponible',
                'energy_rating' => 'A',
                'co2_emissions' => 320,
                'co2_savings' => 2600,
                'energy_type' => 'geotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'sate', 'rainwater_recovery', 'certified_wood', 'eco_paints'],
                'certifications' => ['Passivhaus'],
                'images' => ['/images/properties/chalet-bioclimatico-4.jpg'],
                'is_featured' => true,
            ],
            [
                'title' => 'Estudio Reformado con Eficiencia B en El Carmen',
                'slug' => 'estudio-reformado-eficiencia-b-carmen',
                'description' => "Acogedor estudio completamente reformado en edificio histórico del centro de Valencia. A pesar de las limitaciones del edificio protegido, se ha conseguido certificación B.\n\nReforma realizada con materiales ecológicos, ventanas de alta eficiencia compatibles con la estética del edificio, y sistema de climatización por splits de bajo consumo.\n\nIdeal para inversión o primera vivienda.",
                'price' => 145000,
                'location' => 'El Carmen, Valencia',
                'address' => 'Calle Alta, 8',
                'surface' => 45,
                'rooms' => 1,
                'bathrooms' => 1,
                'year_built' => 2019,
                'property_type' => 'estudio',
                'status' => 'disponible',
                'energy_rating' => 'B',
                'co2_emissions' => 520,
                'co2_savings' => 800,
                'energy_type' => 'electrica',
                'sustainability_features' => ['double_glazing', 'eco_paints'],
                'certifications' => [],
                'images' => ['/images/properties/apartamento-verde-5.jpg'],
                'is_featured' => false,
            ],
            [
                'title' => 'Dúplex con Aerotermia en Paterna',
                'slug' => 'duplex-aerotermia-paterna',
                'description' => "Amplio dúplex de reciente construcción en zona residencial tranquila. Sistema de aerotermia centralizado para calefacción, refrigeración y agua caliente sanitaria.\n\nLa vivienda cuenta con dos plantas conectadas por escalera interior, terraza en planta superior y plaza de garaje con preinstalación para punto de recarga de vehículo eléctrico.\n\nComunidad con zonas verdes y piscina.",
                'price' => 285000,
                'location' => 'Paterna, Valencia',
                'address' => 'Calle del Parque, 45',
                'surface' => 140,
                'rooms' => 3,
                'bathrooms' => 2,
                'year_built' => 2022,
                'property_type' => 'duplex',
                'status' => 'reservada',
                'energy_rating' => 'B',
                'co2_emissions' => 620,
                'co2_savings' => 1400,
                'energy_type' => 'aerotermia',
                'sustainability_features' => ['thermal_insulation', 'double_glazing', 'aerothermy'],
                'certifications' => ['VERDE'],
                'images' => ['/images/properties/casa-pasiva-6.jpg'],
                'is_featured' => true,
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
